CREATE SCHEMA DectectiveSQLGame ;
-- only use DROP if needeed
-- DROP SCHEMA DectectiveSQLGame ;
USE DectectiveSQLGame ;
DROP TABLE IF EXISTS Countries ;
DROP TABLE IF EXISTS Cities ;
DROP TABLE IF EXISTS Dates ;
DROP TABLE IF EXISTS People ;
DROP TABLE IF EXISTS Artifacts ;

CREATE TABLE Countries ( ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(50),
CODE VARCHAR(5),
CAPITAL VARCHAR(50),
Currency VARCHAR(10),
POPULATION DECIMAL(12, 0));

CREATE TABLE Cities ( ID INT PRIMARY KEY NOT NULL, 
CITY_NAME VARCHAR(50),
COUNTRY_ID INT ,
FOREIGN KEY (COUNTRY_ID) REFERENCES Countries(ID)
);

CREATE TABLE Dates (ID INT PRIMARY KEY NOT NULL, 
COUNTRY_ID INT,
VISITING_DATE DATE,
TIME_ENTERING_COUNTRY TIME,
TIME_LEAVING_COUNTRY TIME,
FOREIGN KEY (COUNTRY_ID) REFERENCES Cities(ID)
);

CREATE TABLE People (ID INT PRIMARY KEY NOT NULL, 
PERSON_NAME VARCHAR(50),
COUNTRY_ID INT,
DATE_MET INT,
FOREIGN KEY (DATE_MET) REFERENCES Dates(ID),
FOREIGN KEY (COUNTRY_ID) REFERENCES Countries(ID)
);

CREATE TABLE Artifacts (ID INT PRIMARY KEY NOT NULL,
BELONG_TO INT,
ARTIFACT_NAME VARCHAR(50),
VALUE_OF_ARTIFACT LONG ,
FOREIGN KEY (BELONG_TO) REFERENCES People(ID)
);

SELECT * FROM Countries;
SELECT * FROM Cities;
SELECT * FROM Dates;
SELECT * FROM People;
SELECT * FROM Artifacts;





